# Generated by Django 4.2.6 on 2023-11-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0006_edificacion_avg_calificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificacion',
            old_name='numer_calificacion',
            new_name='number_calificacion',
        ),
    ]
