# Generated by Django 4.2.6 on 2023-11-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0007_rename_numer_calificacion_edificacion_number_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='calficacion',
            new_name='calificacion',
        ),
    ]
